project_name: Monster-efficiency-middlebury
restore_ckpt: "./checkpoints/sceneflow.pth"
logdir: './checkpoints/middlebury/'
encoder: 'vits'
batch_size: 8
train_datasets: ['middlebury_finetune']
lr: 1e-4
wdecay: 1e-5
total_step: 100000
save_frequency: 2000
save_path: "./Output/checkpoints/middlebury"
val_frequency: 2000
image_size: [352, 896]
train_iters: 4
valid_iters: 4
val_dataset: 'kitti'
corr_implementation: "reg"
corr_radius: [2, 2, 4]
n_downsample: 2
n_gru_layers: 3
hidden_dims: [32, 64, 96]
max_disp: 768
saturation_range: [0.0, 1.4]
do_flip: False
spatial_scale: [-0.2, 0.4]
noyjitter: True
num_gpu: 4
seed: 666
