project_name: Monster-efficiency-eth3d
restore_ckpt: "./checkpoints/sceneflow.pth" 
logdir: './checkpoints/eth3d/'
encoder: 'vits'
batch_size: 8
train_datasets: ['eth3d_train']
lr: 2e-4
wdecay: 1e-5
total_step: 200000
save_frequency: 1000
save_path: './Output/checkpoints/eth3d'
val_frequency: 1000
image_size: [416, 800]  #[384, 512]
train_iters: 4
valid_iters: 4
val_dataset: 'eth3d'
corr_implementation: "reg"
corr_radius: [2, 2, 4]
n_downsample: 2
n_gru_layers: 3
hidden_dims: [32, 64, 96]
max_disp: 192
saturation_range: [0.0, 1.4]
do_flip: False
spatial_scale: [-0.2, 0.4]
noyjitter: True
num_gpu: 4
seed: 666
