project_name: Monster-efficiency-kitti
restore_ckpt: "./checkpoints/sceneflow.pth"
logdir: './checkpoints/kitti/'
encoder: 'vits'
batch_size: 12
train_datasets: ['driving_scene']
lr: 1e-4
wdecay: 1e-5
total_step: 50000
save_frequency: 2000
save_path: "./Output/checkpoints/kitti"
val_frequency: 2000
image_size: [352, 1216]
train_iters: 4
valid_iters: 4
val_dataset: ['KITTI_2012', 'KITTI_2015']
corr_implementation: "reg"
corr_radius: [2, 2, 4]
n_downsample: 2
n_gru_layers: 3
hidden_dims: [32, 64, 96]
max_disp: 192
saturation_range: [0.7, 1.3]
do_flip: False
spatial_scale: [-0.2, 0.5]
noyjitter: True
num_gpu: 4
seed: 655
