project_name: Monster-efficiency-sceneflow
restore_ckpt: None
logdir: './checkpoints/sceneflow/'
encoder: 'vits'
batch_size: 12
train_datasets: ['sceneflow']
lr: 2e-4
wdecay: 1e-5
total_step: 250000
save_frequency: 5000
save_path: "./Output/checkpoints/sceneflow"
val_frequency: 5000
image_size: [320, 736]
train_iters: 4
valid_iters: 4
val_dataset: 'sceneflow'
corr_implementation: "reg"
corr_radius: [2, 2, 4]
n_downsample: 2
n_gru_layers: 3
hidden_dims: [32, 64, 96]
max_disp: 192
saturation_range: [0.7, 1.3]
do_flip: False
spatial_scale: [-0.2, 0.5]
noyjitter: True
num_gpu: 4
seed: 666
