project_name: Monster-efficiency-zero_shot
restore_ckpt: "./checkpoints/sceneflow.pth"
logdir: './checkpoints/zero_shot/'
encoder: 'vits'
batch_size: 128
train_datasets: ['zero_shot']
lr: 2e-4
wdecay: 1e-5
total_step: 500000
save_frequency: 2000
save_path: "./Output/checkpoints/zero_shot"
val_frequency: 2000
image_size: [320, 736]
train_iters: 4
valid_iters: 4
val_dataset: ['KITTI_2012', 'KITTI_2015', 'Middlebury', 'ETH3D']
split: "MiddEval3"
resolution: "H"
corr_implementation: "reg"
corr_radius: [2, 2, 4]
n_downsample: 2
n_gru_layers: 3
hidden_dims: [32, 64, 96]
max_disp: 416
saturation_range: [0.7, 1.3]
do_flip: False
spatial_scale: [-0.2, 0.5]
noyjitter: True
num_gpu: 8
seed: 666