project_name: Monster-mix_all
restore_ckpt: "./checkpoints/sceneflow.pth" 
logdir: './checkpoints/mix_all/'
encoder: 'vitl'
batch_size: 64
train_datasets: ['mix_all']
lr: 1e-5
wdecay: 1e-5
total_step: 200000
save_frequency: 2000
save_path: "./output/mixall"
val_frequency: 2000
image_size: [320, 736]
train_iters: 22
valid_iters: 32
val_dataset: ['KITTI_2012', 'KITTI_2015', 'Middlebury', 'ETH3D']
split: "MiddEval3"
resolution: "H"
corr_implementation: "reg"
corr_levels: 2
corr_radius: 4
n_downsample: 2
n_gru_layers: 3
hidden_dims: [128, 128, 128]
max_disp: 416
saturation_range: [0.7, 1.3]
do_flip: False
spatial_scale: [-0.2, 0.5]
noyjitter: True
num_gpu: 8
seed: 666
